Models/Reporting/DupProjectEntry.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Scheduling.Models
{
    public class DupProjectEntry
    {
        public int PubCodeFK { get; set; }
        public int ProjectRangeFK { get; set; }
        public int YearFK {get;set;}
        public int Count {get;set;}
    }
    
}

Models/Reporting/ProjectCreatedCSV.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using FileHelpers;

namespace Scheduling.Models
{
   
    [DelimitedRecord(",")]
     public class ProjectCreatedCSV
     {
         public string ProjectName { get; set; }
         public string CreationDate { get; set; }
         public string TimeOfCreation { get; set; }
         public string Year { get; set; }
         public string ProfileType { get; set; }
     }
}

Models/Reporting/ProjectNewstand.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Scheduling.Models
{
    public class ProjectNewstand
    {
        public string NewstandDate { get; set; }
        public string ProjectName { get; set; }
        public int? ProjectID { get; set; }
    }
}

Models/Reporting/ProjectNewstandCSV.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using FileHelpers;

namespace Scheduling.Models
{
     [DelimitedRecord(",")]
    public class ProjectNewstandCSV
    {
        public string NewstandDate { get; set; }
        public string ProjectName { get; set; }
    }
      
}

Controllers/ReportingController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Web.Mvc;
using Scheduling.Models;
using Scheduling.ActionFilter;
using System.Linq;
using System.Text.RegularExpressions;
using System.Configuration;

namespace Scheduling.Controllers
{
    [CleanUpReportingDirectoryActionFilter]
    public class ReportingController : Controller
    {
        //PDF The Attribute will cause the view to render as a pdf.

        [EO.Pdf.Mvc.RenderAsPDF]
        public ActionResult ProjectsNewsStandPDF()
        {
            List<ProjectNewstand> PnList = Scheduling.Database.Utility.GetProjectNewstandDates();
            return View(PnList);

        }

        public ActionResult AddReportingPresentation()
        {
            ViewBag.ProjectRangeOptions = Scheduling.Html.AdminUtilities.BuildProjectRangeDropdown();
            ViewBag.PubCodeDropdownOptions = Scheduling.Html.AdminUtilities.BuildPublicationDropdown();
            ViewBag.ReportingSubItemOptins = Scheduling.Html.AdminUtilities.BuildReportingSubitemDropdown();

            return View();
        }

        public ActionResult Presentation()
        {
            List<MainSubItemSort> MssList = Scheduling.Database.Utility.GetAllMilestoneFieldMainSubItemsForReportSorting().ToList();
            List<PublicationCode> PubCodes = Scheduling.Database.Utility.GetAllPublicationCodes().OrderBy(x => x.LongDesc).ToList();

            ViewBag.PubCodes = PubCodes;
            return View(MssList);
        }

        public ActionResult DeleteSubSortWithTimelineAndPubcode(FormCollection fc)
        {
            if (!string.IsNullOrWhiteSpace(fc["hfTimeline"]) && !string.IsNullOrWhiteSpace(fc["hfPubcode"]))
            {
                string CurrentPubCode = fc["hfPubcode"];
                string CurrentTimeline = fc["hfTimeline"];
                string DelText = string.Format("delete from dbo.MilestoneFieldMainSubItemsReportSorting where pubcodefk ={0} and projectrangefk={1}", CurrentPubCode, CurrentTimeline);
                Scheduling.Database.Utility.ExecuteNonQueryWrapper(DelText);
            }

            return RedirectToAction("Presentation");
        }


        public ActionResult DeleteSubSortWithPubcodeOnly(FormCollection fc)
        {
            if (!string.IsNullOrWhiteSpace(fc["hfPubcode"]))
            {
                string CurrentPubCode = fc["hfPubcode"];
                string DelText = string.Format("delete from dbo.MilestoneFieldMainSubItemsReportSorting where pubcodefk ={0} and projectrangefk is null", CurrentPubCode);
                Scheduling.Database.Utility.ExecuteNonQueryWrapper(DelText);
            }

            return RedirectToAction("Presentation");

        }

        public ActionResult ProcessAddPresentationSubitems(FormCollection fc)

        {
            string SubItemsDelimitedStr = string.Empty;
            string PubcodeStr = string.Empty;
            string ProjectRangeStr = string.Empty;
            string InsText = string.Empty;

            if (!string.IsNullOrWhiteSpace(fc["hf-report-setup"]))
            {
                SubItemsDelimitedStr = fc["hf-report-setup"];
            }

            if (!string.IsNullOrWhiteSpace(fc["pubcode"]))
            {
                PubcodeStr = fc["pubcode"];
            }

            if (!string.IsNullOrWhiteSpace(fc["project-range"]))
            {
                ProjectRangeStr = fc["project-range"];
            }

            if (!string.IsNullOrWhiteSpace(SubItemsDelimitedStr) && !string.IsNullOrWhiteSpace(PubcodeStr))
            {

                string DelComText = string.Format("delete from dbo.MilestoneFieldMainSubItemsReportSorting where pubcodefk ={0}", PubcodeStr);
                string FilterStr = string.Empty;

                if (!string.IsNullOrWhiteSpace(ProjectRangeStr))
                {
                    FilterStr = string.Format("and projectrangefk = {0}", ProjectRangeStr);


                }

                else
                {
                    //whacks general one
                    FilterStr = "and projectrangefk is null";
                }

                DelComText = string.Concat(DelComText, " ", FilterStr);

                //On the client side we currently require 2 rows so in essence the else statement should not execute

                string ChoppedStr = SubItemsDelimitedStr.Substring(0, SubItemsDelimitedStr.Length - 2);

                List<string> DoublePipeList = new List<string>();

                if (ChoppedStr.Contains("||"))
                {

                    string[] RowArray = ChoppedStr.Split(new string[] { "||" }, StringSplitOptions.None);

                    DoublePipeList = RowArray.ToList<string>();
                }

                else

                {
                    DoublePipeList.Add(ChoppedStr);

                }

                string TotalExcStr = string.Empty;

                foreach (string s in DoublePipeList)
                {
                    string[] PipeArray = s.Split('|');

                    string CurrentInsStr = string.Empty;

                    string SubItemFK = PipeArray[0];
                    string SortOrder = PipeArray[1];

                    if (string.IsNullOrWhiteSpace(ProjectRangeStr))
                    {

                        CurrentInsStr = string.Format("insert into dbo.MilestoneFieldMainSubItemsReportSorting (PubCodeFK,MilestoneFieldMainSubItemFK,SortOrder) values({0},{1},{2});", PubcodeStr, SubItemFK, SortOrder);

                    }

                    else
                    {
                        CurrentInsStr = string.Format("insert into dbo.MilestoneFieldMainSubItemsReportSorting (PubCodeFK,MilestoneFieldMainSubItemFK,SortOrder,ProjectRangeFK) values({0},{1},{2},{3});", PubcodeStr, SubItemFK, SortOrder, ProjectRangeStr);

                    }

                    TotalExcStr = TotalExcStr + CurrentInsStr;

                }

                Scheduling.Database.Utility.ExecuteNonQueryWrapper(DelComText);
                Scheduling.Database.Utility.ExecuteNonQueryWrapper(TotalExcStr);

            }

            return RedirectToAction("Presentation");
        }


        public ActionResult DataIntegrity()
        {
            List<DupProjectEntry> DupEntryList = Scheduling.Database.Utility.GetAllDuplicateProjectEntries();
            return View(DupEntryList);

        }

        [EO.Pdf.Mvc.RenderAsPDF]
        public ActionResult ProjectsCreatedPDF()
        {
            int CreatedStatus = (int)Scheduling.Enums.ProjectStatus.Created;
            List<ProjectDisplay> PdList = Scheduling.Database.Utility.GetAllProjects().Where(x => x.CurrentProjectStatus == CreatedStatus).OrderByDescending(x => x.DateCreated).ToList();

            return View(PdList);
        }


        public ActionResult ExcelStyleReportsCSV(FormCollection fc)
        {
            List<ProjectDisplay> PdList = Scheduling.Database.Utility.GetAllProjects();
            return View(PdList);

        }

        //REGULAR

        public ActionResult ProjectsCreated()
        {
            int CreatedStatus = (int)Scheduling.Enums.ProjectStatus.Created;
            List<ProjectDisplay> PdList = Scheduling.Database.Utility.GetAllProjects().Where(x => x.CurrentProjectStatus == CreatedStatus).OrderByDescending(x => x.DateCreated).ToList();

            return View(PdList);
        }

        public ActionResult ProjectsNewsStand()
        {
            List<ProjectNewstand> PnList = Scheduling.Database.Utility.GetProjectNewstandDates();
            return View(PnList);

        }


        //Rolled in to version 4
        //ExcelStyleReportsFormatRevised.cshmtl (page)
        //Added by --- Tom W.
        [EO.Pdf.Mvc.RenderAsPDF]
        public ActionResult ExcelStyleReportsViewFormatRevised()
        {
            /*User selects fit and landscape */
            /* Best Yet with fit option ratio to width height should be square root of 2 */
            EO.Pdf.HtmlToPdf.Options.PageSize = new System.Drawing.SizeF(17f, 11f);
            EO.Pdf.HtmlToPdf.Options.OutputArea = new System.Drawing.RectangleF(0.1f, 0.1f, 16.8f, 10.8f);

            List<ProjectDisplay> PdList = (List<ProjectDisplay>)Session["ProjectDisplayResultSet"];
            int ReportingYearID = PdList.Select(x => x.YearFK).Min();
            int ReportingYearVal = Scheduling.Database.Utility.GetYearByID(ReportingYearID);
            ViewBag.ReportingYearVal = ReportingYearVal;
            return View(PdList);
        }



        [EO.Pdf.Mvc.RenderAsPDF]
        public ActionResult ExcelStyleReportsPDFReplicateView()
        {
            /*http://www.essentialobjects.com/doc/4/htmltopdf/page_size.aspx*/

            /*User selects fit and landscape */

            /* Best Yet with fit option ratio to width height should be square root of 2 */
            EO.Pdf.HtmlToPdf.Options.PageSize = new System.Drawing.SizeF(17f, 11f);
            EO.Pdf.HtmlToPdf.Options.OutputArea = new System.Drawing.RectangleF(0.1f, 0.1f, 16.8f, 10.8f);

            //removed ref helene 4/16/2014
            // EO.Pdf.HtmlToPdf.Options.HeaderHtmlFormat ="<div style='overflow:hidden' class='header-container'><div style='float:right'>Page {page_number} of &nbsp;{total_pages}</div></div>";
            //On excel style reports view session is set and ordered by SortByPubCodeDescThenYearThenTimeline method in display sorting .Currently Long Desc.
            List<ProjectDisplay> PdList = (List<ProjectDisplay>)Session["ProjectDisplayResultSet"];

            //Get Min Year Should be passed to partial view that does the header
            int ReportingYearID = PdList.Select(x => x.YearFK).Min();
            int ReportingYearVal = Scheduling.Database.Utility.GetYearByID(ReportingYearID);
            ViewBag.ReportingYearVal = ReportingYearVal;
            return View(PdList);

        }
        //set to 7 days
        //disable for now 2/3/2015

Views/Reporting/AddReportingPresentation.cshtml
@{
    ViewBag.Title = "AddReportingPresentation";
    Layout = "~/Views/Shared/_ResponsiveLayout.cshtml";
    int MaxSortOrder = 10;
}

<h2>Add Reporting Presentation</h2>

<p class="italic" style="margin-top:-30px;font-size:1.1em;font-weight:bold;">Since there is no edit facility the logic will overwrite an existing presentation if it exits.</p>

<p>Click the add button to add a sort item after choosing a publication and a timeline (optional)</p>
<div class="container">
    @{ Html.BeginForm("ProcessAddPresentationSubitems", "Reporting", FormMethod.Post, new { enctype = "multipart/form-data", id = "ProcessAddPresentationSubitems" }); }

    <div class="row">
        <div class="eight columns">

            <!--Pubcode-->
            <p style="font-weight:bold">
                Publication
            </p>
            <select name='pubcode' id="pubcode">
                @Html.Raw(ViewBag.PubCodeDropdownOptions)
            </select>
        </div>

        <div class="eight columns">
        
            <!--timeline  -->
            <p style="font-weight:bold">
                Choose Timeline(Optional)
            </p>
            <select name='project-range' id='project-range' class='project-range-presentation'>
                <option value=''>Choose Timeline (optional)</option>
                @Html.Raw(ViewBag.ProjectRangeOptions)
            </select>
           
        </div>
    </div>

    <div class="sixteen columns">

        <img style="display:block;width:50px;margin-bottom:10px" class="add-sort-item" src="@Url.Content("~/images/add-item.png")"> 
    
    </div>

    <div class="row submission clone-me">
        <div class="sixteen columns">
            <div class="four columns">
                <select name="sub-item-select" class="sub-item-select">
                    <option value="">--Choose Subitem--</option>
                    @Html.Raw(ViewBag.ReportingSubItemOptins)
                </select>
            </div>

            <div class="four columns ">
                <select name="sub-sort-select" class="sub-sort-select">
                    <option value="">--Choose Sort Order--</option>
                    @{

                        for (int i = 1; i <= 10; i++)
                        {
                            <option value="@i">@i</option>

                        }


                    }
                </select>
            </div>
        </div>
    </div>
        <!--inject rows here-->
        <div class="inject-me">

        </div>
   

  

    <input type="submit" value="Create Report Setup" class="report-button"/>
    <input type="hidden" value="" class="hf-report-setup" name="hf-report-setup"/>
    

    @{ Html.EndForm(); }

</div>

<script type="text/javascript">

    $(document).ready(function () {


        //globals 
        var numRows = 1;


        //form submit

        $("form").submit(function (event) {


            var numValidRows = GetNumberOfValidRows();



            if (numValidRows < 2)
            {
                alert('Requires at least 2 valid rows');
                return false;
                
            }

           
                GenerateHiddenFieldForSubmission()
            
        });


        
      

        function GenerateHiddenFieldForSubmission()
        {
            var totalStr = '';

            $('.sub-item-select').each(function () {

                var siv = $(this).val();                
                var ov = $(this).parents('.sixteen').find('.sub-sort-select').val();
             
                
                if(siv.length > 0 && ov.length > 0)
                {
                    
                    var currentStr = siv + '|' + ov + '||';
                    totalStr = totalStr + currentStr;
                }

            })
            
            $('.hf-report-setup').val(totalStr);
            

        }

        function GetNumberOfValidRows()
        {
            var validRows = 0;
            $('.sub-item-select').each(function () {

                var siv = $(this).val();                
                var ov = $(this).parents('.sixteen').find('.sub-sort-select').val();
                
                if(siv.length > 0 && ov.length > 0)
                {
                    validRows++;

                }

            }

            );

            return validRows;

        }



        function GenerateSubItemMarkup()
        {
            var injectedHtml = '';
            for (var i = 1; i <= numRows; i++) {

                injectedHtml = injectedHtml + $('.row.clone-me').html();

            }
                        

            $('.inject-me').html(injectedHtml);

        }



        $('.add-sort-item').click(function () {

            var pubVal = $('#pubcode').val();
            if (pubVal.length == 0)
            {
                alert('Please Select Publication Code');
                return;
            }

            numRows++;

            GenerateSubItemMarkup();

        }
        
        )
    });

</script>

Views/Reporting/GenerateReportsFiltered.cshtml
@model Scheduling.Models.ReportProjectDisplayViewModel


@{
    ViewBag.Title = "Generate Reports ";
    Layout = "~/Views/Shared/_ResponsiveLayout.cshtml";
    int NewsstandID = Convert.ToInt32(Scheduling.StringFunctions.Utility.GetAppSettingValue("NewsstandOnSaleDateMilestoneValue"));

}
<!--Used to invoke pdf controller with pdf reporting attribute..click event in reporting.js-->
@{

    if (Model.ProjectDisplayList.Count > 0)
    {
        Session["ProjectDisplayResultSet"] = Model.ProjectDisplayList;

        Html.BeginForm("ExcelStyleReportsPDFNewsStandReportForCirc", "Reporting", FormMethod.Post, new { enctype = "multipart/form-data", id = "ExportToPDF" });
        Html.EndForm();

        Html.BeginForm("ExcelStyleReportsPDFReplicateView", "Reporting", FormMethod.Post, new { enctype = "multipart/form-data", id = "ExportToPDFReplicateView" });
        Html.EndForm();

        Html.BeginForm("ExcelStyleReportsViewFormatRevised", "Reporting", FormMethod.Post, new { enctype = "multipart/form-data", id = "ExportToPDFRevisedView" });
        Html.EndForm();

    }


}
<h5>
    <img src="@Url.Content("~/images/export-to-pdf.jpg")" alt='export-to-pdf' style='width:25px;padding-left:10px' class='export-to-pdf' />
    <span>On Sale Dates</span>
</h5>

<h5>
    <img src="@Url.Content("~/images/export-to-pdf.jpg")" alt='export-to-pdf' style='width:25px;padding-left:10px' class='export-to-pdf-revised-view' /><span>
        Project Production Schedules
    </span>
</h5>
<div class="container excel-style-results-selector">
    <!--Filter By Pubcode And Year-->
    @{ Html.BeginForm("GenerateReportsFiltered", "Reporting", FormMethod.Post, new { enctype = "multipart/form-data", id = "ExcelStyleReportsForm" }); }
    <div class="sixteen columns">
        <!--Filter by pubcode-->
        <div class='four columns'>
            <span class='pubcode-year-filter'>Filter By PubCode and Year</span>
        </div>
        <div class='three columns'>
            <select name='pubcode' class='list-project-select-filter'>
                <option value=''>--Choose Pubcode --</option>
                @Html.Raw(Scheduling.Html.ViewDropdown.BuildPreselectedPublicationDropdown(ViewBag.CurrentPubCode))
            </select>
        </div>
        <div class='three columns'>
            <select name='year' class='list-project-select-filter'>
                <option value=''>-- Choose Year --</option>
                @Html.Raw(Scheduling.Html.ViewDropdown.BuildPreselectedYearDropdownForReporting(ViewBag.CurrentYearCode))
            </select>
        </div>
        <div class='three columns'>
            <input type='submit' class='excel-style-submit-form' />
        </div>
        @{ Html.EndForm(); }
    </div>

    <!--Filter By Pubcode/Timeline Range/Year-->
    @{ Html.BeginForm("GenerateReportsFiltered", "Reporting", FormMethod.Post, new { enctype = "multipart/form-data", id = "ExcelStyleReportsFormFilterByTimelineRange" }); }
    <div class="sixteen columns">
        <!--Filter by pubcode-->
        <div class='four columns'>
            <span class='pubcode-year-filter'>Filter By PubCode/Timeline Range</span>
        </div>
        <div class='three columns'>
            <input type='text' class='monthPicker timelineRangeStart' name='timelineRangeStart' value='@ViewBag.PersistedStart' />
        </div>
        <div class='three columns'>
            <input type='text' class='monthPicker timelineRangeEnd' name='timelineRangeEnd' value='@ViewBag.PersistedStop' />
        </div>
        <div class='three columns'>
            <select name='pubcode-timeline' class='list-project-select-filter-timeline-range' multiple="multiple">
                <option value=''>All Pubcodes</option>
                @Html.Raw(Scheduling.Html.ViewDropdown.BuildPreselectedMultiplePublicationDropdown(ViewBag.CurrentPubCodeList))
            </select>
        </div>
        <div class='two columns'>
            <input type='submit' class='excel-style-submit-form-timeline-range' />
        </div>
        @{ Html.EndForm(); }
    </div>
    <div class='sixteen columns'>
        <div class='error-message'>
        </div>
    </div>
</div>
<div class='excel-style-results'>

    @if (Model.ProjectDisplayList.Count > 0)
    {
             <!--PubCodeSummary-->
        <h5 style="font-style: italic; border-top: 1px solid #ccc; border-bottom: 1px solid #ccc; color: #808080;word-wrap:break-word;">@string.Concat("Pub Code Report Includes ", Model.PubCodeSummary)</h5>


        if (Model.DisplaySections.Count > 0)
        {
            foreach (Scheduling.Models.ReportProjectDisplayViewModelSection sec in Model.DisplaySections)
            {

                <div class="project-container" style="padding-top:40px">
                    <div style="overflow:hidden">
                        <div style="float:left">
                            <h5 class='main-header'>@sec.SectionHeader.YearMonthHeader</h5>
                        </div>

                        <div style='float:left;margin-left:60%;'>

                            <h5 class='main-header'>Revised @sec.SectionHeader.RevisedHeader</h5>
                        </div>

                        <div style='float:right;margin-right:5%;'>

                            <h5 class='main-header'>@sec.SectionHeader.PubcodeHeader</h5>
                        </div>


                    </div>

                    <!--notes start-->

                    @if (sec.SectionHeader.NotesAreAvailable)
                    {

                        <table>
                          
                            <tr>
                                <td style='border: none'></td>
                                @if (!string.IsNullOrEmpty(sec.SectionHeader.KPCProjectNumber))
                                {

                                    <td colspan="4" style="border:none;font-weight:bold">
                                        @string.Concat("KPC Project Number: ",sec.SectionHeader.KPCProjectNumber)

                                    </td>
                                }

                                @if (!string.IsNullOrEmpty(sec.SectionHeader.QuadJobNumber))
                                {

                                    <td colspan="4" style="border:none;font-weight:bold">
                                        @string.Concat("Quad Job #: ", sec.SectionHeader.QuadJobNumber)

                                    </td>
                                }

                                @if (!string.IsNullOrEmpty(sec.SectionHeader.NextIssueCrossPromoNumber))
                                {

                                    <td colspan="4" style="border:none;font-weight:bold">
                                      @string.Concat("Next Issue And Cross Promo Ads: ", sec.SectionHeader.NextIssueCrossPromoNumber);

                                    </td>
                                }


                            </tr>

                        </table>

                    }

                    <!--notes stop-->

                    <!--top item container start-->

                    <table class="top-item-container">
                        <tr>
                            <td class='empty'></td>
                            @{
                                foreach (Scheduling.Models.MilestoneDisplayRecord mdr in sec.TopRecords)
                                {
                                    <td class="@mdr.CssClass">@mdr.Description</td>

                                }

                            }

                        </tr>

                        <tr class="parent-due-date">
                            <td class='empty'></td>
                            @{
                                foreach (Scheduling.Models.MilestoneDisplayRecord mdr in sec.TopRecords)
                                {
                                    <td class="parent-due-date">@mdr.Value</td>

                                }

                            }

                        </tr>

                    </table>

                    <!--sub items-->

                    @if (sec.SubItemRows.Count > 0)
                    {
                        <table class="calculation">

                            @foreach (Scheduling.Models.SubItemRow sir in sec.SubItemRows)
                            {
                                <tr>
                                    <td style="width:100px">@sir.Description</td>


                                    @foreach (string s in sir.SubItemDates)
                                    {
                                        <td class="calcValue" style="text-align:center;font-size:1.1em">@s</td>

                                    }
                                </tr>
                            }

                        </table>

                    }

                    <!--sub items stop-->
                    
                </div>

                                        }

                                    }


                                }

    @if (Model.ProjectDisplayList.Count == 0 && ViewBag.InitialLoad == "N")
    {
        <p style='font-weight: bold'>
            No matching results
        </p>

    }


</div>
<script src=@Url.Content("~/Scripts/Bundled/DatepickerMonthOnly.js") type="text/javascript"></script>
<script src=@Url.Content("~/Scripts/Bundled/lodash.js") type="text/javascript"></script>

<!--test mode defined in globalvars-->
<script type='text/javascript'>

    $(document).ready(function () {

        $('table.calculation tbody tr:nth-child(odd)').css('background-color', '#ccc');

        //client side val on pubcode/year submit

        //prepopulate
        //$('.timelineRangeStart').val('2016-01');
        //$('.timelineRangeEnd').val('2017-02');

        $('#ExcelStyleReportsForm').submit(function () {

            $('.error-message').html('');

            var pubcodeSel = $('#ExcelStyleReportsForm select.list-project-select-filter').eq(0);

            var yearSel = $('#ExcelStyleReportsForm select.list-project-select-filter').eq(1);

            var pubcodeSelVal = $(pubcodeSel).val();
            var yearSelVal = $(yearSel).val();

            //use lodash library for ease of detection (better than isNan(parseInt) !

            if (_.size(pubcodeSelVal) > 0 && _.size(yearSelVal) > 0) {

                return true;
            }

            else {
                $('.error-message').html('Please Choose A Pubcode And Year');
                return false;
            }





        });


        //date range validation done on datepickermonthonly js file

    });

</script>

Views/Reporting/ProjectsCreated.cshtml
@model List<Scheduling.Models.ProjectDisplay>
@{
    ViewBag.Title = "Created Projects";
    Layout = "~/Views/Shared/_ResponsiveLayout.cshtml";
}

<!--used to invoke controllers-->
@{ 
    Html.BeginForm("ProjectsCreatedPDF", "Reporting", FormMethod.Post, new { enctype = "multipart/form-data", id = "ExportToPDF" }); 
    Html.EndForm();

    Html.BeginForm("ProjectsCreatedCSV", "Reporting", FormMethod.Post, new { enctype = "multipart/form-data", id = "ExportToCSV" });
    Html.EndForm();
    
}

<h2>
    There are @Model.Count Current Projects With A Project Status of Created.
    
    <img src="@Url.Content("~/images/export-to-pdf.jpg")" alt='export-to-pdf' style='width:25px;padding-left:10px' class='export-to-pdf'/>

      <img src="@Url.Content("~/images/export-to-csv.jpg")" alt='export-to-csv' style='width:25px;padding-left:10px' class='export-to-csv'/>
</h2>

@{
    
    
    if (Model.Count > 0)
    {
        
    <table cellspacing='0' cellpadding='0' class='zebra-striped'>
        <thead>
            <tr style='background-color: #808080'>
                <th align='left'>
                    Project Name
                </th>
                <th align='left'>
                    Creation Date
                </th>
                <th align='left'>
                    Time of Creation
                </th>
                <th align='left'>
                    Year
                </th>
                <th align='left'>
                    Profile Type
                </th>
            </tr>
        </thead>
        <tbody>
            @{
                  

        foreach (Scheduling.Models.ProjectDisplay pd in Model)
        {

                <tr>
                    <td style='width: 15%'>@pd.Name
                    </td>
                    <td style='width: 15%'>@pd.DateCreated.ToLongDateString()
                    </td>
                    <td style='width: 15%'>@pd.DateCreated.ToShortTimeString()
                    </td>
                    <td style='width: 15%'>@Scheduling.Database.Utility.GetAllYears().Where(x => x.ID == pd.YearFK).First().Value
                    </td>
                    <td style='width: 15%'>@Scheduling.Database.Utility.GetProfileTypeNameFromProjectID(pd.ID)
                    </td>
                </tr>

        }
                   
            }
        </tbody>
    </table>

        
        
    }
    
}

Views/Reporting/ProjectsNewsStand.cshtml
@model List<Scheduling.Models.ProjectNewstand>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_ResponsiveLayout.cshtml";
}
<h2>
    There are @Model.Count Current Projects With News Stand Dates

     <img src="@Url.Content("~/images/export-to-pdf.jpg")" alt='export-to-pdf' style='width:25px;padding-left:10px' class='export-to-pdf'/>

      <img src="@Url.Content("~/images/export-to-csv.jpg")" alt='export-to-csv' style='width:25px;padding-left:10px' class='export-to-csv'/>
</h2>


<!--used to invoke controllers-->
@{ 
    Html.BeginForm("ProjectsCreatedPDF", "Reporting", FormMethod.Post, new { enctype = "multipart/form-data", id = "ExportToPDF" }); 
    Html.EndForm();

    Html.BeginForm("ProjectsCreatedCSV", "Reporting", FormMethod.Post, new { enctype = "multipart/form-data", id = "ExportToCSV" });
    Html.EndForm();
    
}


@{
    
    <!--use zebra-striped class for row-styling'-->
    
    if (Model.Count > 0)
    {
        
    <table cellspacing='0' cellpadding='0' class='zebra-striped'>
        <thead>
            <tr style='background-color: #808080'>
                <th>
                    Project
                </th>
                <th>
                    N/S Date
                </th>
            </tr>
        </thead>
        <tbody>
            @{
                  

        foreach (Scheduling.Models.ProjectNewstand pn in Model)
        {
                        
                <tr>
                    <td style='width: 25%'>@pn.ProjectName
                    </td>
                    <td style='width: 25%'>@pn.NewstandDate
                    </td>
                </tr>

        }
                   
                   
            }
        </tbody>
    </table>

        
        
    }
    
}