Models/Linking/ProjectLink.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Scheduling.Models
{
    public class ProjectLink
    {
        public int ID { get; set; }
        public int PrimaryProjectID { get; set; }
        public int SecondaryProjectID { get; set; }
        public int LinkSettingID { get; set; }
    }

    public class ProjectLinkDisplay
    {
        public int ID { get; set; }
        public string PrimaryProject { get; set; }
        public string SecondaryProject { get; set; }
        public string PrimaryProjectProfileType { get; set; }
        public string SecondaryProjectProfileType { get; set; }
        public int PrimaryProjectID { get; set; }
        public int SecondaryProjectID { get; set; }
    }
}

Models/Linking/ProjectLinkSetting.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Scheduling.Models
{
    public class ProjectLinkSetting
    {
        public int ID { get; set; }
        public int PrimaryProfileTypeID { get; set; }        
        public int PrimaryMilestoneID { get; set; }        
        public int SecondaryProfileTypeID { get; set; }
        public int SecondaryMilestoneID { get; set; }
        [Required]
        public int CalculationID { get; set; }
        public int? PubCode { get; set; }
        public int? Timeline { get; set; }
        [Required]
        public string Name { get; set; }
       
    }

    public class ProjectLinkSettingDisplay
    {
        public int ID { get; set; }
        public string PrimaryProfileType { get; set; }
        public string PrimaryMilestone { get; set; }
        public string SecondaryProfileType { get; set; }
        public string SecondaryMilestone { get; set; }
        public string Calculation { get; set; }
        public string PubCode { get; set; }
        public string Timeline { get; set; }
        public string Name { get; set; }
    }
}

Models/Linking/ProjectLinkViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Scheduling.Models
{
    public class ProjectLinkViewModel
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Year { get; set; }
        public string PubCodeName { get; set; }
        public int? PubCodeID { get; set; }
        public int YearFK { get; set; }
    }
}

Controllers/LinkingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Scheduling.Database;
using Scheduling.Models;

namespace Scheduling.Controllers
{
    public class LinkingController : Controller
    {
        public ActionResult ListLinkSettings()
        {
            List<ProjectLinkSetting> SettingList = Utility.GetAllProjectLinkSettings();
            List<ProjectLinkSettingDisplay> DisList = Scheduling.CastingFunctions.Utility.ConvertProjectLinkSettingToDisplay(SettingList);

            return View(DisList);

        }

        public ActionResult ManageLinkSettings()
        {
            List<ProjectLinkSetting> SettingList = Utility.GetAllProjectLinkSettings();
            List<ProjectLinkSettingDisplay> DisList = Scheduling.CastingFunctions.Utility.ConvertProjectLinkSettingToDisplay(SettingList);

            return View(DisList);

        }

        public ActionResult DeleteSingleProjectLinkEntry(int id)
        {
            Scheduling.Database.Utility.DeleteSingleProjectLinkAndKeepValues(id);
            return RedirectToAction("ManageLinkedProjects");

        }

        public ActionResult DeleteSingleProjectLinkEntryAndRemoveSecondaryValues(int id)
        {
            Scheduling.Database.Utility.DeleteSingleProjectLinkAndResetValues(id);            
            return RedirectToAction("ManageLinkedProjects");

        }




        public ActionResult ProcessAddLinkSetting(ProjectLinkSetting pls)
        {
            if (pls.PrimaryProfileTypeID == pls.SecondaryProfileTypeID)
            {
                ModelState.AddModelError("SecondaryProfileTypeID","Primary(Source) and Target(Secondary) profiles need to be DIFFERENT");

            }

            
            if(ModelState.IsValid)
            {

                Scheduling.Database.Utility.CreateNewLinkSetting(pls);
                return RedirectToAction("ManageLinkSettings");
            }

            else
            {

                List<PublicationCode> PubCodeList = Scheduling.Database.Utility.GetAllPublicationCodes(); ViewBag.PubCodeList = PubCodeList;
                List<MilestoneField> ParentMilestoneList = Scheduling.Database.Utility.GetAllParentMilestoneFields(); ViewBag.ParentMilestoneList = ParentMilestoneList;
                List<ProjectProfileType> ProjectProfileTypeList = Scheduling.Database.Utility.GetAllProjectProfileTypes(); ViewBag.ProjectProfileTypeList = ProjectProfileTypeList;
                List<Timeline> Timelines = Scheduling.Database.Utility.GetAllProjectRanges(); ViewBag.Timelines = Timelines;
                List<Calculation> Calculations = Scheduling.Database.Utility.GetAllCalculationFields(); ViewBag.Calculations = Calculations;
                return View("AddLinkSetting");
            }

            
            
        }

        public ActionResult AddLinkSetting()
        {
            
            List<PublicationCode> PubCodeList = Scheduling.Database.Utility.GetAllPublicationCodes();  ViewBag.PubCodeList = PubCodeList;
            List<MilestoneField>  ParentMilestoneList = Scheduling.Database.Utility.GetAllParentMilestoneFields(); ViewBag.ParentMilestoneList = ParentMilestoneList;
            List<ProjectProfileType> ProjectProfileTypeList = Scheduling.Database.Utility.GetAllProjectProfileTypes(); ViewBag.ProjectProfileTypeList = ProjectProfileTypeList;
            List<Timeline> Timelines = Scheduling.Database.Utility.GetAllProjectRanges(); ViewBag.Timelines = Timelines;
            List<Calculation> Calculations = Scheduling.Database.Utility.GetAllCalculationFields(); ViewBag.Calculations = Calculations;
            return View();
        }

        public ActionResult DeleteSingleLinkSetting(FormCollection fc)
        {
            int CurrentSetting = Convert.ToInt32(fc["id"]);
            Scheduling.Database.Utility.DeleteSingleLinkSetting(CurrentSetting);
            return RedirectToAction("ManageLinkSettings");
        }

        public ActionResult ManageSingleProjectLinking(FormCollection fc)
        {

            int CurrentProject = Convert.ToInt32(fc["id"]);
            ViewBag.CurrentProject = CurrentProject;
            List<ProjectLinkSetting> Settinglist = Scheduling.Database.Utility.GetProjectLinkSettingsByProjectID(CurrentProject);
            return View(Settinglist);

        }

        public ActionResult   ManageLinkedProjects()
        {
           List<ProjectLink> ProjList=Scheduling.Database.Utility.GetAllProjectLinks();
           List<ProjectLinkDisplay> RetList=Scheduling.CastingFunctions.Utility.ConvertProjectLinkToDisplay(ProjList);
           return View(RetList);
        }

      
        //Verify not sure if this is still used.
        public ActionResult ProcessManageSingleProjectLinking(FormCollection fc)
        {

            if(Scheduling.StringFunctions.Utility.GetAppSettingValue("LinkAndCalculate").ToLower()=="false")
            {
                Scheduling.Linking.Utility.ManageSingleProjectLinkingAddAndCreateInitialTopLevelEntry(fc);
            }

            else 

            {
                Scheduling.Linking.Utility.ManageSingleProjectLinkingAddAndCreateAllEntries(fc);
            }

            int RetID = Convert.ToInt32(fc["current-project"]);
            return RedirectToAction("ManageSingleProjectAfterDependencyAjaxCall", "Home", new { id = RetID, message = string.Empty });

        }
     
    }
}

Views/Linking/AddLinkSetting.cshtml
@*  Prepopulate Primary Profile and field with magazine and n/s on sale date   *@

@{
    ViewBag.Title = "Add Link Settings";
    Layout = "~/Views/Shared/_ResponsiveLayout.cshtml";
}

<div class="container linkaddition">
    @Html.ValidationSummary()
    @{ Html.BeginForm("ProcessAddLinkSetting", "Linking", FormMethod.Post, new { enctype = "multipart/form-data", id = "AddLinkSetting" }); }
    <div class="sixteen columns scroll-to-on-load">
        <h2>Add Link Setting</h2>
        <h4>Step 1... Choose Source Profile Type and Milestone</h4>

        <div class="seven columns alpha">

            <p>Primary Project Profile</p>

            <select name="PrimaryProfileTypeID">
                @foreach (Scheduling.Models.ProjectProfileType ppt in ViewBag.ProjectProfileTypeList)
                {

                    if (ppt.ID == Convert.ToInt32(Scheduling.StringFunctions.Utility.GetAppSettingValue("MagazineProjectType")))
                    {
                        <option selected="selected" value="@ppt.ID">@ppt.Description</option> }

                    else
                    {
                        <option value="@ppt.ID">@ppt.Description</option>

                    }

                }

            </select>
        </div>

        <div class="seven columns">


            <p>Primary Milestone Field</p>

            <select name="PrimaryMilestoneID">
                @foreach (Scheduling.Models.MilestoneField mf in ViewBag.ParentMilestoneList)
                {
                    if (mf.ID == Convert.ToInt32(Scheduling.StringFunctions.Utility.GetAppSettingValue("NewsstandOnSaleDateMilestoneValue")))
                    {
                <option selected="selected" value="@mf.ID">@mf.Description</option> }

                    else
                    {
                <option value="@mf.ID">@mf.Description</option>

                    }

                }

            </select>
        </div>


    </div>
    <div class="sixteen columns">

        <h4>Step 2... Choose Target Profile Type and Milestone</h4>

        <div class="seven columns alpha">

            <p>Secondary Project Profile</p>

            <select name="SecondaryProfileTypeID">
                @foreach (Scheduling.Models.ProjectProfileType ppt in ViewBag.ProjectProfileTypeList)
                {
                    <option value="@ppt.ID">@ppt.Description</option>
                }

            </select>
        </div>

        <div class="seven columns">


            <p>Primary Milestone Field</p>

            <select name="SecondaryMilestoneID">
                @foreach (Scheduling.Models.MilestoneField mf in ViewBag.ParentMilestoneList)
                {
                    <option value="@mf.ID">@mf.Description</option>

                }

            </select>
        </div>


    </div>
    <div class="sixteen columns">
        <h4>Step 3 </h4>
        <div class="five columns alpha">
            <p>Name of Setting</p>
            <input name="Name" type="text" />

        </div>

    </div>

    <div class="sixteen columns">
        
        <div class="seven columns alpha">
        <h4>Step 4..(Optional PubCode)</h4>
            <select name="PubCode">
                @{
                    <option value="">--N/A--</option>
                    foreach (Scheduling.Models.PublicationCode pc in ViewBag.PubCodeList)
                    {
                <option value="@pc.ID">@pc.ShortDesc</option>

                    }

                }
            </select>

        </div>

        <div class="seven columns">
            <h4>(Optional Timeline)</h4>
            <select name="Timeline">
                @{
                    <option value="">--N/A--</option>
                    foreach (Scheduling.Models.Timeline t in ViewBag.Timelines)
                    {
                <option value="@t.ID">@t.ShortDesc</option>

                    }

                }
            </select>

        </div>

    </div>
    <div class="sixteen columns">
        <h4>Step 5..Calculation</h4>
        <select name="CalculationID">
            <option value=''>--Choose Calculation</option>
            @foreach (Scheduling.Models.Calculation c in ViewBag.Calculations)
            {
                <option value="@c.ID">@c.ShortDesc</option>
            }
        </select>
    </div>

    <div class='add-single-submit-container'>
        <input type="submit" value='Add Link Setting' />
    </div>
    @{ Html.EndForm(); }
</div>

Views/Linking/ListLinkSettings.cshtml
@model List<Scheduling.Models.ProjectLinkSettingDisplay>

@{
    ViewBag.Title = "List Link Settings";
    Layout = "~/Views/Shared/_ResponsiveLayout.cshtml";
}

<div class='container'>
    <div class='sixteen columns scroll-to-on-load'>
        @{
            if (Model.Count > 0)
            {
            
            @Html.Partial("_TableHeaderPartial", ViewData["header"] = "Link Settings")
                
            <table class='condensed zebra-striped' id='results'>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>
                           Primary Profile Type
                        </th>
                        <th>Primary Milestone</th>
                          <th>
                           Secondary Profile Type
                        </th>
                        <th>Secondary Milestone</th>
                        <th>Calculation Offset</th>
                        <th>Publication Code</th>
                        <th>Timeline(Month)</th>
                        
                    </tr>
                </thead>
                <tbody class='group-pagination'>
                    @{  foreach (Scheduling.Models.ProjectLinkSettingDisplay s in Model)
                        { 
           
                        <tr>
                            <td>@s.Name</td>
                            <td>@s.PrimaryProfileType
                            </td>
                             <td>@s.PrimaryMilestone
                            </td>
                             <td>@s.SecondaryProfileType</td>
                             <td>@s.SecondaryMilestone
                            </td>
                            <td>@s.Calculation</td>
                            <td>@s.PubCode</td>
                            <td>@s.Timeline</td>
                        </tr>
      
         
                        }
     
                    }
                </tbody>
            </table> 
 
        

            }
            
            else
            {
                <p style="font-style:italic">There are no current settings</p>
                
            }


        }

       
    </div>
    <div id="pageNavPosition">
    </div>
      <script type="text/javascript"><!--
          var pager = new Pager('results', 10);
          pager.init();
          pager.showPageNav('pager', 'pageNavPosition');
          pager.showPage(1);
    </script>
</div>

Views/Linking/ManageLinkSettings.cshtml
@model List<Scheduling.Models.ProjectLinkSettingDisplay>

@{
    ViewBag.Title = "Manage Link Settings";
    Layout = "~/Views/Shared/_ResponsiveLayout.cshtml";
}

<div class='container'>

    <div class='sixteen columns'>
    <p style='font-style:italic'>Only Link Settings that are NOT assigned to projects can be deleted</p>
    </div>

    <!--automatically invoked find out why todo -->
    <div class='sixteen columns'>
    <a href='/linking/addlinksetting' title='Add Link Setting'><img alt='add-link-setting' src="@Url.Content("~/images/add-item.png")" width='30px' style='display:block;padding:10px 0px' class='img-add-link-setting'/></a>
    
    </div>
    <div class='sixteen columns scroll-to-on-load'>
        @{
            if (Model.Count > 0)
            {
            
            @Html.Partial("_TableHeaderPartial", ViewData["header"] = "Manage Link Settings")
                
            <table class='condensed zebra-striped' id='results'>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>
                           Primary Profile Type
                        </th>
                        <th>Primary Milestone</th>
                          <th>
                           Secondary Profile Type
                        </th>
                        <th>Secondary Milestone</th>
                        <th>Calculation Offset</th>
                        <th>Publication Code</th>
                        <th>Timeline(Month)</th>
                        
                    </tr>
                </thead>
                <tbody class='group-pagination'>
                    @{  foreach (Scheduling.Models.ProjectLinkSettingDisplay s in Model)
                        { 
           
                        <tr>
                            <td>@s.Name</td>
                            <td>@s.PrimaryProfileType
                            </td>
                             <td>@s.PrimaryMilestone
                            </td>
                             <td>@s.SecondaryProfileType</td>
                             <td>@s.SecondaryMilestone
                            </td>
                            <td>@s.Calculation</td>
                            <td>@s.PubCode</td>
                            <td>@s.Timeline</td>
                            <td>
                             @if (Scheduling.Database.Utility.IsLinkSettingAvailableForDeletion(s.ID))
                             {
                                 Html.BeginForm("DeleteSingleLinkSetting", "Linking", FormMethod.Post, new { enctype = "multipart/form-data", name = "DeleteGroupEntry", id = "DeleteGroupEntry" });

                                 <input type='hidden' value='@s.ID' name="id" />
                                 <img src="@Url.Content("~/images/remove-item.png")"  alt='remove item' style='width:30px' class='remove-link-setting'/>
                                 
                                 Html.EndForm();

                             }
                             
                            </td>
                        </tr>
      
         
                        }
     
                    }
                </tbody>
            </table> 
 
        

            }

            else
            {
                <p style="font-style:italic">There are no current settings</p>
                
            }


        }

       
    </div>
    <div id="pageNavPosition">
    </div>
      <script type="text/javascript"><!--
          var pager = new Pager('results', 10);
          pager.init();
          pager.showPageNav('pager', 'pageNavPosition');
          pager.showPage(1);
    </script>
</div>

Views/Linking/ManageLinkedProjects.cshtml
@model List<Scheduling.Models.ProjectLinkDisplay>
@{
    ViewBag.Title = "Manage Linked Projects";
    Layout = "~/Views/Shared/_ResponsiveLayout.cshtml";


}
@{
    if (Model.Count == 0)
    {
    <p class='italic'>
        There Are No Linked Project Entries</p>
                
                
    }
            
            
}
<div class='container'>

   
    <div class='sixteen columns'>
        @{
            
        
            
            if (Model.Count > 0)
            {
            
                
            @Html.Partial("_TableHeaderPartial", ViewData["header"] = "Linked Projects")
                
            <table class='condensed zebra-striped' id='results'>
                <thead>
                    <tr>
                        <th>
                            Primary Project
                        </th>
                        <th>
                            Primary Profile Type
                        </th>
                        <th>
                            Secondary Project
                        </th>
                        <th>
                            Secondary Profile Type
                        </th>
                        <th>Remove Link Only</th>
                        <th>Remove Link/Reset Secondary Values</th>
                    </tr>
                </thead>
                <tbody class='group-pagination'>
                    @{  foreach (Scheduling.Models.ProjectLinkDisplay d in Model)
                        { 
           
                        <tr>
                            <td>@d.PrimaryProject
                            </td>
                            <td>@d.PrimaryProjectProfileType
                            </td>
                            <td>@d.SecondaryProject
                            </td>
                            <td>@d.SecondaryProjectProfileType
                            </td>
                            <td>
                                
                                @{ Html.BeginForm("DeleteSingleProjectLinkEntry", "Linking", FormMethod.Post, new { enctype = "multipart/form-data", name = "DeleteSingleProjectLinkEntry" }); }
                                <img src="@Url.Content("~/images/remove-project.png")" alt='remove-project-link' style='width:30px;display:block;margin:0 auto'
                                    class='remove-project-link' title='remove link and keep date values'/>
                                <input type='hidden' value='@d.ID' name='id'/>
                                <input type='hidden' value='@d.PrimaryProjectID' name='PrimaryProjectID' />
                                <input type='hidden' value='@d.SecondaryProjectID' name='SecondaryProjectID' />
                                @{ Html.EndForm(); }
                            </td>
                             <td>
                                @{ Html.BeginForm("DeleteSingleProjectLinkEntryAndRemoveSecondaryValues", "Linking", FormMethod.Post, new { enctype = "multipart/form-data", name = "DeleteSingleProjectLinkEntry" }); }
                                <img src="@Url.Content("~/images/remove-project.png")" alt='remove-project-link' style='width:30px;display:block;margin:0 auto'
                                    class='remove-project-link remove-project-link-reset-values' title='remove link and whack values !!!!!'/>
                                <input type='hidden' value='@d.ID' name='id'/>
                                <input type='hidden' value='@d.PrimaryProjectID' name='PrimaryProjectID' />
                                <input type='hidden' value='@d.SecondaryProjectID' name='SecondaryProjectID' />
                                @{ Html.EndForm(); }
                            </td>
                        </tr>
      
         
                        }
     
                    }
                </tbody>
            </table> 
 
        

            }


        }
    </div>
    <div id="pageNavPosition">
    </div>
    <script type="text/javascript"><!--
        var pager = new Pager('results', 10);
        pager.init();
        pager.showPageNav('pager', 'pageNavPosition');
        pager.showPage(1);
    </script>
</div>

Views/Linking/ManageSingleProjectLinking.cshtml
@model List<Scheduling.Models.ProjectLinkSetting>
@{
    ViewBag.Title = "Manage Single Project Linking";
    Layout = "~/Views/Shared/_ResponsiveLayout.cshtml";
    int CurrentProject = (int)ViewBag.CurrentProject;
    string CurrentProjectName = Scheduling.Database.Utility.GetAllProjects().Where(x => x.ID == CurrentProject).First().Name;
}

@{ Html.BeginForm("ProcessManageSingleProjectLinking", "Linking", FormMethod.Post, new { enctype = "multipart/form-data", id = "ProcessMangageSingleProjectLinking" }); }

<h2>
    Manage Single Project Linking for @CurrentProjectName
</h2>
<div class='choose-link-setting'>
    <h4>
        Step 1 Choose Link Setting(s)</h4>
    <select name='link-setting-select' class='link-setting-select'>
        @{
            <option value=''>--Choose--</option>
            foreach (Scheduling.Models.ProjectLinkSetting pls in Model)
            {
           
            <option value='@pls.ID'>@pls.Name</option>
    
            }
   
    
        }
    </select>
</div>
<div class='link-setting-select-project'>
</div>
<div class='link-setting-project-submission' style='display: none'>
    <input type='hidden' value='@CurrentProject' name='current-project' />
    <input type='hidden' value='' name='chosen-linkable-project' class='chosen-linkable-project' />
    <input type='hidden' value='@CurrentProjectName' class='current-project-name' name='current-project-name'/>
    <input type='hidden' value='' class='chosen-setting-link' name='chosen-setting-link' />
    <input type='submit' value='Link Projects' />
    @{ Html.EndForm();}
</div>